* Software Heritage - GekkoFS benchmarks

** How to run
The job runs via executing the =job.sh= script on the first note of a slurm job.
Different parameters like the file system to use can be adjusted within the *parameter* section of the =job.sh= script.


1. Build and install GekkoFS following the official instructions.
2. Build Software Heritage following the official instructions.
3. Adjust hardcoded paths within =job.sh= to your environment.
3. Adjust the parameters =PARAM_x= within =job.sh= to your liking.
   within =job.sh= to your environment.
4. ssh into the first note of your reservation and execute the =job.sh= script.

For convenience, a single job running =job.sh= can be scheduled via =shedule_and_observe_single_job.sh=.
Multiple jobs with permuting parameters can be configured and executed via =shedule_jobs.sh=.

** Sample Results Torino Cluster
#+begin_src bash
Cachemire=1, Cachemire dir PFS, 8 Nodes: 3130s
Cachemire=1, Cachemire dir local RAM, 8 Nodes: 67s
Cachemire=1, Cachemire dir GKFS, 8 Nodes: 83s
Cachemire=0, 8 Nodes: 67s
#+end_src
