.PHONY: all

amd64:
	docker build --platform amd64 -t gekkofs/testing:0.9.3-exp .

aarch64:
	docker build --platform aarch64 -t gekkofs/testing:0.9.3-exp .

all:
	docker build -t gekkofs/testing:0.9.3-exp .
